from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8('MainWindow'))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 479)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.main_widget = QtGui.QWidget(MainWindow)
        self.main_widget.setAutoFillBackground(False)
        self.main_widget.setObjectName(_fromUtf8('main_widget'))
        self.query_button = QtGui.QPushButton(self.main_widget)
        self.query_button.setGeometry(QtCore.QRect(580, 10, 211, 51))
        self.query_button.setObjectName(_fromUtf8('query_button'))
        self.response_table = QtGui.QTableView(self.main_widget)
        self.response_table.setGeometry(QtCore.QRect(9, 250, 781, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.response_table.sizePolicy().hasHeightForWidth())
        self.response_table.setSizePolicy(sizePolicy)
        self.response_table.setSortingEnabled(False)
        self.response_table.setWordWrap(True)
        self.response_table.setObjectName(_fromUtf8('response_table'))
        self.response_table.horizontalHeader().setCascadingSectionResizes(True)
        self.response_table.horizontalHeader().setMinimumSectionSize(30)
        self.response_table.horizontalHeader().setSortIndicatorShown(False)
        self.response_table.horizontalHeader().setStretchLastSection(False)
        self.response_table.verticalHeader().setCascadingSectionResizes(True)
        self.response_table.verticalHeader().setSortIndicatorShown(False)
        self.layoutWidget = QtGui.QWidget(self.main_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 561, 62))
        self.layoutWidget.setObjectName(_fromUtf8('layoutWidget'))
        self.top_layout = QtGui.QHBoxLayout(self.layoutWidget)
        self.top_layout.setObjectName(_fromUtf8('top_layout'))
        self.last_name_layout = QtGui.QVBoxLayout()
        self.last_name_layout.setObjectName(_fromUtf8('last_name_layout'))
        self.last_name_label = QtGui.QLabel(self.layoutWidget)
        self.last_name_label.setMaximumSize(QtCore.QSize(16777215, 82))
        self.last_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.last_name_label.setObjectName(_fromUtf8('last_name_label'))
        self.last_name_layout.addWidget(self.last_name_label)
        self.last_name = QtGui.QLineEdit(self.layoutWidget)
        self.last_name.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.last_name.setObjectName(_fromUtf8('last_name'))
        self.last_name_layout.addWidget(self.last_name)
        self.top_layout.addLayout(self.last_name_layout)
        self.first_name_layout = QtGui.QVBoxLayout()
        self.first_name_layout.setObjectName(_fromUtf8('first_name_layout'))
        self.first_name_label = QtGui.QLabel(self.layoutWidget)
        self.first_name_label.setMaximumSize(QtCore.QSize(16777215, 82))
        self.first_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_name_label.setObjectName(_fromUtf8('first_name_label'))
        self.first_name_layout.addWidget(self.first_name_label)
        self.first_name = QtGui.QLineEdit(self.layoutWidget)
        self.first_name.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.first_name.setObjectName(_fromUtf8('first_name'))
        self.first_name_layout.addWidget(self.first_name)
        self.top_layout.addLayout(self.first_name_layout)
        self.patr_name_layout = QtGui.QVBoxLayout()
        self.patr_name_layout.setObjectName(_fromUtf8('patr_name_layout'))
        self.patr_name_label = QtGui.QLabel(self.layoutWidget)
        self.patr_name_label.setMaximumSize(QtCore.QSize(16777215, 82))
        self.patr_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patr_name_label.setObjectName(_fromUtf8('patr_name_label'))
        self.patr_name_layout.addWidget(self.patr_name_label)
        self.patr_name = QtGui.QLineEdit(self.layoutWidget)
        self.patr_name.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.patr_name.setObjectName(_fromUtf8('patr_name'))
        self.patr_name_layout.addWidget(self.patr_name)
        self.top_layout.addLayout(self.patr_name_layout)
        self.sex_layout = QtGui.QVBoxLayout()
        self.sex_layout.setObjectName(_fromUtf8('sex_layout'))
        self.sex_label = QtGui.QLabel(self.layoutWidget)
        self.sex_label.setMaximumSize(QtCore.QSize(16777215, 82))
        self.sex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_label.setObjectName(_fromUtf8('sex_label'))
        self.sex_layout.addWidget(self.sex_label)
        self.sex = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.sex.setSizePolicy(sizePolicy)
        self.sex.setBaseSize(QtCore.QSize(100, 0))
        self.sex.setMaxVisibleItems(2)
        self.sex.setMaxCount(3)
        self.sex.setObjectName(_fromUtf8('sex'))
        self.sex.addItem(_fromUtf8(''))
        self.sex.addItem(_fromUtf8(''))
        self.sex_layout.addWidget(self.sex)
        self.top_layout.addLayout(self.sex_layout)
        self.layoutWidget1 = QtGui.QWidget(self.main_widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 781, 91))
        self.layoutWidget1.setObjectName(_fromUtf8('layoutWidget1'))
        self.middle_layout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.middle_layout.setObjectName(_fromUtf8('middle_layout'))
        self.birth_date_layout = QtGui.QVBoxLayout()
        self.birth_date_layout.setObjectName(_fromUtf8('birth_date_layout'))
        self.birth_date_label = QtGui.QLabel(self.layoutWidget1)
        self.birth_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.birth_date_label.setObjectName(_fromUtf8('birth_date_label'))
        self.birth_date_layout.addWidget(self.birth_date_label)
        self.birth_date_data_layout = QtGui.QHBoxLayout()
        self.birth_date_data_layout.setObjectName(_fromUtf8('birth_date_data_layout'))
        self.birth_date_from_layout = QtGui.QVBoxLayout()
        self.birth_date_from_layout.setObjectName(_fromUtf8('birth_date_from_layout'))
        self.birth_date_from_label = QtGui.QLabel(self.layoutWidget1)
        self.birth_date_from_label.setAlignment(QtCore.Qt.AlignCenter)
        self.birth_date_from_label.setObjectName(_fromUtf8('birth_date_from_label'))
        self.birth_date_from_layout.addWidget(self.birth_date_from_label)
        self.birth_date_from = QtGui.QLineEdit(self.layoutWidget1)
        self.birth_date_from.setMinimumSize(QtCore.QSize(100, 0))
        self.birth_date_from.setMaximumSize(QtCore.QSize(100, 16777215))
        self.birth_date_from.setBaseSize(QtCore.QSize(0, 0))
        self.birth_date_from.setFrame(True)
        self.birth_date_from.setObjectName(_fromUtf8('birth_date_from'))
        self.birth_date_from_layout.addWidget(self.birth_date_from)
        self.birth_date_data_layout.addLayout(self.birth_date_from_layout)
        self.birth_date_to_layout = QtGui.QVBoxLayout()
        self.birth_date_to_layout.setObjectName(_fromUtf8('birth_date_to_layout'))
        self.birth_date_to_label = QtGui.QLabel(self.layoutWidget1)
        self.birth_date_to_label.setAlignment(QtCore.Qt.AlignCenter)
        self.birth_date_to_label.setObjectName(_fromUtf8('birth_date_to_label'))
        self.birth_date_to_layout.addWidget(self.birth_date_to_label)
        self.birth_date_to = QtGui.QLineEdit(self.layoutWidget1)
        self.birth_date_to.setMinimumSize(QtCore.QSize(100, 0))
        self.birth_date_to.setMaximumSize(QtCore.QSize(100, 16777215))
        self.birth_date_to.setBaseSize(QtCore.QSize(0, 0))
        self.birth_date_to.setFrame(True)
        self.birth_date_to.setObjectName(_fromUtf8('birth_date_to'))
        self.birth_date_to_layout.addWidget(self.birth_date_to)
        self.birth_date_data_layout.addLayout(self.birth_date_to_layout)
        self.birth_date_layout.addLayout(self.birth_date_data_layout)
        self.middle_layout.addLayout(self.birth_date_layout)
        self.document_layout = QtGui.QVBoxLayout()
        self.document_layout.setObjectName(_fromUtf8('document_layout'))
        self.document_label = QtGui.QLabel(self.layoutWidget1)
        self.document_label.setAlignment(QtCore.Qt.AlignCenter)
        self.document_label.setObjectName(_fromUtf8('document_label'))
        self.document_layout.addWidget(self.document_label)
        self.document_data_layout = QtGui.QHBoxLayout()
        self.document_data_layout.setObjectName(_fromUtf8('document_data_layout'))
        self.document_type_layout = QtGui.QVBoxLayout()
        self.document_type_layout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.document_type_layout.setObjectName(_fromUtf8('document_type_layout'))
        self.document_type_label = QtGui.QLabel(self.layoutWidget1)
        self.document_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.document_type_label.setObjectName(_fromUtf8('document_type_label'))
        self.document_type_layout.addWidget(self.document_type_label)
        self.document_type = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.document_type.sizePolicy().hasHeightForWidth())
        self.document_type.setSizePolicy(sizePolicy)
        self.document_type.setBaseSize(QtCore.QSize(300, 0))
        self.document_type.setMaxVisibleItems(10)
        self.document_type.setMaxCount(250)
        self.document_type.setObjectName(_fromUtf8('document_type'))
        self.document_type_layout.addWidget(self.document_type)
        self.document_data_layout.addLayout(self.document_type_layout)
        self.document_serial_layout = QtGui.QVBoxLayout()
        self.document_serial_layout.setObjectName(_fromUtf8('document_serial_layout'))
        self.document_serial_label = QtGui.QLabel(self.layoutWidget1)
        self.document_serial_label.setAlignment(QtCore.Qt.AlignCenter)
        self.document_serial_label.setObjectName(_fromUtf8('document_serial_label'))
        self.document_serial_layout.addWidget(self.document_serial_label)
        self.document_serial = QtGui.QLineEdit(self.layoutWidget1)
        self.document_serial.setMinimumSize(QtCore.QSize(50, 0))
        self.document_serial.setMaximumSize(QtCore.QSize(60, 16777215))
        self.document_serial.setBaseSize(QtCore.QSize(60, 31))
        self.document_serial.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.document_serial.setFrame(True)
        self.document_serial.setObjectName(_fromUtf8('document_serial'))
        self.document_serial_layout.addWidget(self.document_serial)
        self.document_data_layout.addLayout(self.document_serial_layout)
        self.document_number_layout = QtGui.QVBoxLayout()
        self.document_number_layout.setObjectName(_fromUtf8('document_number_layout'))
        self.document_number_label = QtGui.QLabel(self.layoutWidget1)
        self.document_number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.document_number_label.setObjectName(_fromUtf8('document_number_label'))
        self.document_number_layout.addWidget(self.document_number_label)
        self.document_number = QtGui.QLineEdit(self.layoutWidget1)
        self.document_number.setMinimumSize(QtCore.QSize(70, 0))
        self.document_number.setMaximumSize(QtCore.QSize(80, 16777215))
        self.document_number.setBaseSize(QtCore.QSize(80, 0))
        self.document_number.setObjectName(_fromUtf8('document_number'))
        self.document_number_layout.addWidget(self.document_number)
        self.document_data_layout.addLayout(self.document_number_layout)
        self.document_layout.addLayout(self.document_data_layout)
        self.middle_layout.addLayout(self.document_layout)
        self.layoutWidget_2 = QtGui.QWidget(self.main_widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 150, 428, 87))
        self.layoutWidget_2.setObjectName(_fromUtf8('layoutWidget_2'))
        self.bottom_layout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.bottom_layout.setObjectName(_fromUtf8('bottom_layout'))
        self.age_layout = QtGui.QVBoxLayout()
        self.age_layout.setObjectName(_fromUtf8('age_layout'))
        self.age_label = QtGui.QLabel(self.layoutWidget_2)
        self.age_label.setAlignment(QtCore.Qt.AlignCenter)
        self.age_label.setObjectName(_fromUtf8('age_label'))
        self.age_layout.addWidget(self.age_label)
        self.age_data_layout = QtGui.QHBoxLayout()
        self.age_data_layout.setObjectName(_fromUtf8('age_data_layout'))
        self.age_from_layout = QtGui.QVBoxLayout()
        self.age_from_layout.setObjectName(_fromUtf8('age_from_layout'))
        self.age_from_label = QtGui.QLabel(self.layoutWidget_2)
        self.age_from_label.setAlignment(QtCore.Qt.AlignCenter)
        self.age_from_label.setObjectName(_fromUtf8('age_from_label'))
        self.age_from_layout.addWidget(self.age_from_label)
        self.age_from = QtGui.QLineEdit(self.layoutWidget_2)
        self.age_from.setMinimumSize(QtCore.QSize(100, 0))
        self.age_from.setMaximumSize(QtCore.QSize(100, 16777215))
        self.age_from.setBaseSize(QtCore.QSize(0, 0))
        self.age_from.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.age_from.setFrame(True)
        self.age_from.setObjectName(_fromUtf8('age_from'))
        self.age_from_layout.addWidget(self.age_from)
        self.age_data_layout.addLayout(self.age_from_layout)
        self.age_to_layout = QtGui.QVBoxLayout()
        self.age_to_layout.setObjectName(_fromUtf8('age_to_layout'))
        self.age_to_label = QtGui.QLabel(self.layoutWidget_2)
        self.age_to_label.setAlignment(QtCore.Qt.AlignCenter)
        self.age_to_label.setObjectName(_fromUtf8('age_to_label'))
        self.age_to_layout.addWidget(self.age_to_label)
        self.age_to = QtGui.QLineEdit(self.layoutWidget_2)
        self.age_to.setMinimumSize(QtCore.QSize(100, 0))
        self.age_to.setMaximumSize(QtCore.QSize(100, 16777215))
        self.age_to.setBaseSize(QtCore.QSize(0, 0))
        self.age_to.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.age_to.setFrame(True)
        self.age_to.setObjectName(_fromUtf8('age_to'))
        self.age_to_layout.addWidget(self.age_to)
        self.age_data_layout.addLayout(self.age_to_layout)
        self.age_layout.addLayout(self.age_data_layout)
        self.bottom_layout.addLayout(self.age_layout)
        self.document_layout1 = QtGui.QVBoxLayout()
        self.document_layout1.setObjectName(_fromUtf8('document_layout1'))
        self.snils_label = QtGui.QLabel(self.layoutWidget_2)
        self.snils_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snils_label.setObjectName(_fromUtf8('snils_label'))
        self.document_layout1.addWidget(self.snils_label)
        self.snils_data_layout = QtGui.QHBoxLayout()
        self.snils_data_layout.setObjectName(_fromUtf8('snils_data_layout'))
        self.snils_number_layout = QtGui.QVBoxLayout()
        self.snils_number_layout.setObjectName(_fromUtf8('snils_number_layout'))
        self.snils_number_label = QtGui.QLabel(self.layoutWidget_2)
        self.snils_number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snils_number_label.setObjectName(_fromUtf8('snils_number_label'))
        self.snils_number_layout.addWidget(self.snils_number_label)
        self.snils_number = QtGui.QLineEdit(self.layoutWidget_2)
        self.snils_number.setMinimumSize(QtCore.QSize(200, 0))
        self.snils_number.setMaximumSize(QtCore.QSize(80, 16777215))
        self.snils_number.setBaseSize(QtCore.QSize(80, 0))
        self.snils_number.setInputMethodHints(QtCore.Qt.ImhNone)
        self.snils_number.setObjectName(_fromUtf8('snils_number'))
        self.snils_number_layout.addWidget(self.snils_number)
        self.snils_data_layout.addLayout(self.snils_number_layout)
        self.document_layout1.addLayout(self.snils_data_layout)
        self.bottom_layout.addLayout(self.document_layout1)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.query_button.raise_()
        self.response_table.raise_()
        self.layoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8('menubar'))
        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)
        self.sex.setCurrentIndex(-1)
        self.document_type.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate('MainWindow', '\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80 \xd0\xb4\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd1\x85 \xd0\xbe \xd0\xbf\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x85', None))
        self.query_button.setText(_translate('MainWindow', '\xd0\x9f\xd0\xbe\xd0\xb8\xd1\x81\xd0\xba \xd0\xbf\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb5\xd0\xbd\xd1\x82\xd0\xbe\xd0\xb2', None))
        self.last_name_label.setText(_translate('MainWindow', '\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f', None))
        self.first_name_label.setText(_translate('MainWindow', '\xd0\x98\xd0\xbc\xd1\x8f', None))
        self.patr_name_label.setText(_translate('MainWindow', '\xd0\x9e\xd1\x82\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe', None))
        self.sex_label.setText(_translate('MainWindow', '\xd0\x9f\xd0\xbe\xd0\xbb', None))
        self.sex.setItemText(0, _translate('MainWindow', '\xd0\xbc\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9', None))
        self.sex.setItemText(1, _translate('MainWindow', '\xd0\xb6\xd0\xb5\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9', None))
        self.birth_date_label.setText(_translate('MainWindow', '\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x80\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f', None))
        self.birth_date_from_label.setText(_translate('MainWindow', '\xd1\x81', None))
        self.birth_date_to_label.setText(_translate('MainWindow', '\xd0\xbf\xd0\xbe', None))
        self.document_label.setText(_translate('MainWindow', '\xd0\x94\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82', None))
        self.document_type_label.setText(_translate('MainWindow', '\xd1\x82\xd0\xb8\xd0\xbf', None))
        self.document_serial_label.setText(_translate('MainWindow', '\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f', None))
        self.document_number_label.setText(_translate('MainWindow', '\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80', None))
        self.age_label.setText(_translate('MainWindow', '\xd0\x92\xd0\xbe\xd0\xb7\xd1\x80\xd0\xb0\xd1\x81\xd1\x82', None))
        self.age_from_label.setText(_translate('MainWindow', '\xd1\x81', None))
        self.age_to_label.setText(_translate('MainWindow', '\xd0\xbf\xd0\xbe', None))
        self.snils_label.setText(_translate('MainWindow', '\xd0\xa1\xd0\x9d\xd0\x98\xd0\x9b\xd0\xa1', None))
        self.snils_number_label.setText(_translate('MainWindow', '\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80', None))

